import { useState, useMemo, memo } from "react";
import { useLang } from "./LanguageContext";
import { JORDAN_DNS } from "./data";

// ═══ PUBG Mobile domains — extracted from existing PAC scripts in project repos ═══
const PUBG_DOMAINS = {
  game: ["pubgmobile.com","igamecj.com","proximabeta.com","tencentgames.com","tencent.com","levelinfinite.com","battlegroundsmobileindia.com","krafton.com","bluehole.net"],
  auth: ["qq.com","midasbuy.com","unipay.com","tpns.tencent.com","passport.com","account.levelinfinite.com"],
  cdn: ["akamaized.net","steamcontent.com","steamstatic.com","fastly.net"],
  direct: ["apple.com","icloud.com","google.com","gstatic.com","googleapis.com","youtube.com","facebook.com","instagram.com","whatsapp.com","telegram.org","twitter.com","x.com","tiktok.com","microsoft.com","windowsupdate.com","spotify.com","cloudflare.com","amazon.com"],
};

// ═══ Jordan CIDRs — from existing project data ═══
const JO_CIDRS = [
  "46.32.0.0/15","46.185.128.0/17","77.245.0.0/18","80.90.160.0/19",
  "82.212.64.0/18","86.108.0.0/16","91.106.96.0/19","92.253.0.0/16",
  "94.142.32.0/19","109.237.192.0/18","176.28.0.0/15","176.29.0.0/16",
  "213.186.160.0/19","37.75.144.0/21","37.202.64.0/18",
];

// ═══ Known proxies from existing PAC scripts ═══
const KNOWN_PROXIES = [
  { host: "195.133.14.222", port: 49152, name: "NL Primary", source: "Proxypower/01.pac" },
  { host: "139.59.1.14", port: 8080, name: "IN Backup", source: "Proxypower/01.pac" },
];

type RoutingMode = "DIRECT" | "PROXY" | "AUTO";

export const PacGenerator = memo(function PacGenerator() {
  const { lang } = useLang();
  const ar = lang === "ar";
  const [mode, setMode] = useState<RoutingMode>("DIRECT");
  const [selectedProxy, setSelectedProxy] = useState(0);
  const [includeIPv6, setIncludeIPv6] = useState(false);
  const [includeJoCidrs, setIncludeJoCidrs] = useState(true);
  const [showPreview, setShowPreview] = useState(false);
  const [testHost, setTestHost] = useState("");
  const [copied, setCopied] = useState(false);

  // DNS from project
  const topDns = useMemo(() => {
    const jordanDns = JORDAN_DNS.filter(d => !d.ip.includes(":")).slice(0, 3);
    return jordanDns.map(d => d.ip);
  }, []);

  // Generate PAC script
  const pacScript = useMemo(() => {
    const proxy = KNOWN_PROXIES[selectedProxy];
    const proxyStr = mode === "PROXY" ? `PROXY ${proxy.host}:${proxy.port}` : "DIRECT";
    const now = new Date().toISOString();

    const lines: string[] = [];
    lines.push("/*");
    lines.push(" * PUBG Mobile Network Routing PAC");
    lines.push(" * Generated by: ALYAZOURI 2026 PAC Generator");
    lines.push(` * Routing Mode: ${mode}`);
    if (mode === "PROXY") lines.push(` * Proxy: ${proxy.host}:${proxy.port} (${proxy.name})`);
    lines.push(` * DNS Profile: ${topDns[0] || "System Default"}`);
    lines.push(` * IPv4 Jordan CIDRs: ${includeJoCidrs ? JO_CIDRS.length : 0}`);
    lines.push(` * IPv6: ${includeIPv6 ? "Enabled" : "Disabled"}`);
    lines.push(` * Generated: ${now}`);
    lines.push(" * Security: PUBG protection traffic is NOT modified.");
    lines.push(" */");
    lines.push("");
    lines.push("function FindProxyForURL(url, host) {");
    lines.push("  host = (host || \"\").toLowerCase();");
    lines.push("");
    lines.push("  // === SECURITY: Private/local networks → DIRECT ===");
    lines.push("  if (!host || isPlainHostName(host)) return \"DIRECT\";");
    lines.push("  if (isInNet(host, \"10.0.0.0\", \"255.0.0.0\") ||");
    lines.push("      isInNet(host, \"172.16.0.0\", \"255.240.0.0\") ||");
    lines.push("      isInNet(host, \"192.168.0.0\", \"255.255.0.0\") ||");
    lines.push("      isInNet(host, \"127.0.0.0\", \"255.0.0.0\")) {");
    lines.push("    return \"DIRECT\";");
    lines.push("  }");
    lines.push("");

    // Always-direct domains (CDN, social, etc.)
    lines.push("  // === Always DIRECT (CDN, social, updates) ===");
    lines.push("  var directDomains = [");
    PUBG_DOMAINS.direct.forEach((d, i) => {
      lines.push(`    "${d}"${i < PUBG_DOMAINS.direct.length - 1 ? "," : ""}`);
    });
    lines.push("  ];");
    lines.push("  for (var i = 0; i < directDomains.length; i++) {");
    lines.push("    if (dnsDomainIs(host, directDomains[i])) return \"DIRECT\";");
    lines.push("  }");
    lines.push("");

    if (mode !== "DIRECT") {
      // PUBG game domains → PROXY
      lines.push("  // === PUBG Game Services → Route via proxy ===");
      lines.push("  var gameDomains = [");
      [...PUBG_DOMAINS.game, ...PUBG_DOMAINS.auth].forEach((d, i, arr) => {
        lines.push(`    "${d}"${i < arr.length - 1 ? "," : ""}`);
      });
      lines.push("  ];");
      lines.push("  for (var j = 0; j < gameDomains.length; j++) {");
      lines.push("    if (dnsDomainIs(host, gameDomains[j]) || shExpMatch(host, \"*.\" + gameDomains[j])) {");
      if (mode === "AUTO") {
        lines.push(`      return "${proxyStr}; DIRECT";`);
      } else {
        lines.push(`      return "${proxyStr}";`);
      }
      lines.push("    }");
      lines.push("  }");
      lines.push("");
    }

    if (includeJoCidrs && mode !== "DIRECT") {
      lines.push("  // === Jordan CIDRs → Boost priority ===");
      JO_CIDRS.forEach(cidr => {
        const [ip, bits] = cidr.split("/");
        const maskMap: Record<string, string> = {
          "15": "255.254.0.0", "16": "255.255.0.0", "17": "255.255.128.0",
          "18": "255.255.192.0", "19": "255.255.224.0", "21": "255.255.248.0",
        };
        const mask = maskMap[bits] || "255.255.0.0";
        lines.push(`  if (isInNet(host, "${ip}", "${mask}")) return "${proxyStr}; DIRECT";`);
      });
      lines.push("");
    }

    lines.push("  // === Default: DIRECT ===");
    lines.push("  return \"DIRECT\";");
    lines.push("}");

    return lines.join("\n");
  }, [mode, selectedProxy, includeIPv6, includeJoCidrs, topDns]);

  // PAC validation
  const validation = useMemo(() => {
    const errors: string[] = [];
    if (!pacScript.includes("FindProxyForURL")) errors.push("Missing FindProxyForURL");
    if (!pacScript.includes("DIRECT")) errors.push("No DIRECT fallback");
    if (mode === "PROXY" && !pacScript.includes("PROXY")) errors.push("PROXY mode but no proxy in script");
    const dupCheck = new Set<string>();
    pacScript.split("\n").forEach(line => {
      if (line.trim().startsWith("if") && dupCheck.has(line.trim())) errors.push("Duplicate rule detected");
      dupCheck.add(line.trim());
    });
    return { valid: errors.length === 0, errors };
  }, [pacScript, mode]);

  // Test a host against the PAC logic
  const testResult = useMemo(() => {
    if (!testHost) return null;
    const h = testHost.toLowerCase();
    if (PUBG_DOMAINS.direct.some(d => h.includes(d))) return { rule: "Always DIRECT (CDN/social)", result: "DIRECT" };
    if ([...PUBG_DOMAINS.game, ...PUBG_DOMAINS.auth].some(d => h.includes(d))) {
      return { rule: "PUBG Game Service", result: mode === "DIRECT" ? "DIRECT" : mode === "PROXY" ? `PROXY ${KNOWN_PROXIES[selectedProxy].host}:${KNOWN_PROXIES[selectedProxy].port}` : "PROXY → DIRECT fallback" };
    }
    return { rule: "Default", result: "DIRECT" };
  }, [testHost, mode, selectedProxy]);

  const download = () => {
    const blob = new Blob([pacScript], { type: "application/x-ns-proxy-autoconfig" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `PUBG_ROUTING_${mode}_${new Date().toISOString().slice(0, 10)}.pac`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyPac = () => {
    try { navigator.clipboard?.writeText(pacScript); } catch { /* */ }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-5">
      <div className="text-center">
        <h2 className="font-display text-2xl font-black text-white sm:text-3xl">
          {ar ? "🔧 مولّد PAC Script" : "🔧 PAC Script Generator"}
        </h2>
        <p className="mt-2 text-sm text-white/50">{ar ? "إنشاء PAC احترافي من بيانات المشروع" : "Generate professional PAC from project data"}</p>
      </div>

      {/* Step 1: Routing Mode */}
      <div className="card neon-box rounded-2xl p-5">
        <div className="mb-3 text-xs font-bold text-orange-300">STEP 1 — {ar ? "وضع التوجيه" : "Routing Mode"}</div>
        <div className="grid grid-cols-3 gap-2">
          {(["DIRECT", "PROXY", "AUTO"] as const).map(m => (
            <button key={m} onClick={() => setMode(m)}
              className={`rounded-xl p-3 text-center transition-all ${mode === m ? "bg-orange-500/20 ring-2 ring-orange-400/50" : "bg-white/5 hover:bg-white/10"}`}>
              <div className="text-lg">{m === "DIRECT" ? "🔗" : m === "PROXY" ? "🛡️" : "⚡"}</div>
              <div className="mt-1 text-xs font-bold text-white">{m}</div>
              <div className="text-[9px] text-white/40">
                {m === "DIRECT" ? (ar ? "اتصال مباشر" : "Direct connection") :
                 m === "PROXY" ? (ar ? "عبر بروكسي" : "Via proxy") :
                 (ar ? "تلقائي" : "Auto select")}
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Step 2: Proxy Selection (if PROXY/AUTO) */}
      {mode !== "DIRECT" && (
        <div className="card rounded-2xl p-5">
          <div className="mb-3 text-xs font-bold text-orange-300">STEP 2 — {ar ? "اختيار البروكسي" : "Proxy Selection"}</div>
          <div className="text-[9px] text-white/30 mb-3">{ar ? "المصدر: PAC scripts من مستودعات المشروع" : "Source: PAC scripts from project repositories"}</div>
          {KNOWN_PROXIES.map((p, i) => (
            <button key={i} onClick={() => setSelectedProxy(i)}
              className={`w-full mb-2 rounded-xl p-3 text-left transition-all ${selectedProxy === i ? "bg-emerald-500/15 ring-1 ring-emerald-400/30" : "bg-white/5 hover:bg-white/10"}`}>
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-xs font-bold text-white">{p.name}</div>
                  <code className="text-[10px] text-emerald-300 font-mono">{p.host}:{p.port}</code>
                </div>
                <div className="text-right">
                  <div className="text-[9px] text-white/40">{p.source}</div>
                  {selectedProxy === i && <span className="text-emerald-300 text-xs">✓</span>}
                </div>
              </div>
            </button>
          ))}
        </div>
      )}

      {/* Step 3: Options */}
      <div className="card rounded-2xl p-5">
        <div className="mb-3 text-xs font-bold text-orange-300">STEP 3 — {ar ? "الخيارات" : "Options"}</div>
        <div className="space-y-3">
          <label className="flex items-center justify-between rounded-xl bg-white/5 p-3">
            <span className="text-xs text-white">{ar ? "تضمين CIDRs الأردنية" : "Include Jordan CIDRs"} ({JO_CIDRS.length})</span>
            <button onClick={() => setIncludeJoCidrs(!includeJoCidrs)}
              className={`relative h-6 w-11 rounded-full transition-colors ${includeJoCidrs ? "bg-emerald-500" : "bg-white/20"}`}>
              <span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition-all ${includeJoCidrs ? "left-5" : "left-0.5"}`} />
            </button>
          </label>
          <label className="flex items-center justify-between rounded-xl bg-white/5 p-3">
            <span className="text-xs text-white">{ar ? "دعم IPv6" : "IPv6 Support"}</span>
            <button onClick={() => setIncludeIPv6(!includeIPv6)}
              className={`relative h-6 w-11 rounded-full transition-colors ${includeIPv6 ? "bg-emerald-500" : "bg-white/20"}`}>
              <span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition-all ${includeIPv6 ? "left-5" : "left-0.5"}`} />
            </button>
          </label>
        </div>
      </div>

      {/* Summary */}
      <div className="card rounded-2xl p-5">
        <div className="mb-3 text-xs font-bold text-orange-300">{ar ? "ملخص التهيئة" : "Configuration Summary"}</div>
        <div className="grid grid-cols-2 gap-2 text-[10px]">
          {[
            [ar ? "الوضع" : "Mode", mode],
            [ar ? "البروكسي" : "Proxy", mode === "DIRECT" ? "None" : `${KNOWN_PROXIES[selectedProxy].host}:${KNOWN_PROXIES[selectedProxy].port}`],
            ["PUBG Domains", `${PUBG_DOMAINS.game.length + PUBG_DOMAINS.auth.length}`],
            ["Direct Domains", `${PUBG_DOMAINS.direct.length}`],
            ["Jordan CIDRs", includeJoCidrs ? `${JO_CIDRS.length}` : "0"],
            ["IPv6", includeIPv6 ? "Yes" : "No"],
            [ar ? "الحالة" : "Status", validation.valid ? "✅ VALID" : "❌ ERRORS"],
            [ar ? "الأمان" : "Security", "✅ PUBG protection untouched"],
          ].map(([k, v], i) => (
            <div key={i} className="flex justify-between border-b border-white/5 pb-1">
              <span className="text-white/40">{k}</span>
              <span className="font-bold text-white">{v}</span>
            </div>
          ))}
        </div>
      </div>

      {/* PAC Tester */}
      <div className="card rounded-2xl p-5">
        <div className="mb-3 text-xs font-bold text-orange-300">{ar ? "اختبار القواعد" : "Rule Tester"}</div>
        <div className="flex gap-2 mb-3">
          <input value={testHost} onChange={e => setTestHost(e.target.value)}
            placeholder={ar ? "أدخل domain للاختبار..." : "Enter domain to test..."}
            className="flex-1 rounded-lg bg-black/30 border border-white/10 px-3 py-2 text-xs text-white placeholder-white/30 focus:outline-none focus:border-orange-400/50" />
          <button onClick={() => setTestHost("pubgmobile.com")} className="btn-ghost rounded-lg px-3 py-2 text-[10px]">PUBG</button>
          <button onClick={() => setTestHost("google.com")} className="btn-ghost rounded-lg px-3 py-2 text-[10px]">Google</button>
        </div>
        {testResult && (
          <div className="rounded-xl border border-white/10 bg-black/20 p-3">
            <div className="flex justify-between text-[10px]">
              <span className="text-white/40">{ar ? "القاعدة" : "Rule"}:</span>
              <span className="font-bold text-amber-300">{testResult.rule}</span>
            </div>
            <div className="flex justify-between text-[10px] mt-1">
              <span className="text-white/40">{ar ? "النتيجة" : "Result"}:</span>
              <span className="font-bold text-emerald-300">{testResult.result}</span>
            </div>
          </div>
        )}
      </div>

      {/* Preview + Actions */}
      <div className="flex gap-2">
        <button onClick={() => setShowPreview(!showPreview)} className="btn-ghost flex-1 rounded-xl py-3 text-xs font-bold">
          {showPreview ? (ar ? "▲ إخفاء" : "▲ Hide") : (ar ? "▼ عرض الكود" : "▼ Preview Code")}
        </button>
        <button onClick={copyPac} className="btn-ghost flex-1 rounded-xl py-3 text-xs font-bold">
          {copied ? "✅" : "📋"} {ar ? "نسخ" : "Copy"}
        </button>
        <button onClick={download} disabled={!validation.valid} className="btn-primary flex-1 rounded-xl py-3 text-xs font-bold disabled:opacity-50">
          📥 {ar ? "تحميل PAC" : "Download PAC"}
        </button>
      </div>

      {/* Code Preview */}
      {showPreview && (
        <div className="card rounded-2xl p-4">
          <pre className="rounded-xl bg-black/50 border border-white/5 p-4 text-[10px] text-emerald-300/80 font-mono leading-relaxed overflow-x-auto max-h-80 overflow-y-auto whitespace-pre">
            {pacScript}
          </pre>
          <div className="mt-2 text-[9px] text-white/30">{pacScript.split("\n").length} {ar ? "سطر" : "lines"} · {(pacScript.length / 1024).toFixed(1)}KB</div>
        </div>
      )}

      {/* Validation Errors */}
      {!validation.valid && (
        <div className="card rounded-xl p-3 border-red-500/30 bg-red-500/5">
          <div className="text-xs font-bold text-red-300 mb-1">⚠️ {ar ? "أخطاء" : "Validation Errors"}</div>
          {validation.errors.map((e, i) => <div key={i} className="text-[10px] text-red-300/70">• {e}</div>)}
        </div>
      )}
    </div>
  );
});
